# Generated by Django 5.2.9 on 2026-01-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('PUBLISHED', 'Published'), ('CLAIM_REQUESTED', 'Claim Requested'), ('MATCH_FOUND', 'Match Found'), ('VERIFIED', 'Verified')], default='PENDING', max_length=20),
        ),
    ]
