# Generated by Django 5.2.9 on 2026-01-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('PUBLISHED', 'Published'), ('CLAIM_REQUESTED', 'Claim Requested'), ('MATCH_FOUND', 'Match Found'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
