# Generated by Django 5.2.9 on 2026-04-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_user_email_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ai_keywords',
            field=models.TextField(blank=True, help_text='Auto-generated by AI', null=True),
        ),
    ]
