# Generated by Django 5.2.9 on 2026-04-19 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auditlog_item_claim_proof_alter_item_ai_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_images/gallery/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='api.item')),
            ],
        ),
    ]
