# Generated by Django 5.2.9 on 2026-05-04 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_notification_item_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='request_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='claim',
            name='proof_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='api.item'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
